### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by jessequinn** [zenvia/zenvia-sdk-go#1]
Is there any future for this SDK?

**Comment by rafael-org** [comment]
Hi, Jessequinn,

This SDK has not been implemented, and currently we have no plans for this, but PRs are always welcome. We'll inform this in the README.

For now, we only support SDKs listed here: https://zenvia.github.io/zenvia-openapi-spec/v1/#section/SDKs

We'll count the demand for a GO SDK using +1 reactions on this issue. Then perhaps we will give it a GO 🥁

Anyway, the API is simple to use with any language just using HTTP requests.

**Comment by jessequinn** [comment]
for sure, thanks.
