### ISSUE TITLE
What is the text length limit?

### ISSUE THREAD

**Issue by odilonjk** [zenvia/zenvia-sdk-go#3]
I saw you guys have a test for cases in which the payload has a text too long. However, I didn't found which is this limit.

Test I found: https://github.com/zenvia/zenvia-sdk-go/blob/e7a908aca8638b991866e1af1f4585d3520dfc7e/send_message_test.go#L109

Thanks!

**Comment by rafael-org** [comment]
I do not know why there is such test, perhaps @alexgarzao can clarify. But on the API we do not have any hard limit no the text because the limit varies by channel, and usually they are quite high.

Even SMS which is has a 160/70 limit depending on the characters used, if will send a longer message, it will still be delivered (but it will cost more because concatened SMS is used behind the scenes).

**Comment by odilonjk** [comment]
It would be great to have documented here or in your [specification](https://zenvia.github.io/zenvia-openapi-spec/v2/#tag/SMS) about it. At least I didn't found anything about messages longer than the limit being delivered with increased costs.

If you guys can give me more details about this situation using SMS, I really appreciate it.

Thanks @rafael-org !! :D

**Comment by rafael-org** [comment]
Thanks for the suggestion. We indeed had a discussion about it and back then it was decided that a technical documentation was not the place for this kind of information. Perhaps we should revisit the issue.

As for how it works, when a carrier sends the message to the device, it can be done using one of these charsets: GSM7 (in most countries, but some countries use a different 7-bit charset) or UCS-2 (its like a draft for UTF-16).

In our API, the encodingStrategy MORE_CHARACTERS_PER_MESSAGE means GSM7, which has a limit of 160 characters per message (each character uses 7 bits), and MORE_CHARACTER_SUPPORT means UCS-2, which has a limit of 70 characters per message (each character uses 16 bits). The default encodingStrategy AUTO, means that the charset used will be chosen based on the content of the message.

In both cases, if the text length is longer than these limits, the message will be split in multiple messages using a special header so the device concatenate them into a single message. This is the reason for the increased cost. This header eats up around 7 bytes from the message (I don't recall the exact number), so the amount of characters per message is reduced when using concatenated SMS.

**Comment by odilonjk** [comment]
Excellent! Thanks for the info @rafael-org 
We're already implementing the service on our side. Soon we'll be using your SDK to send SMS.
